// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtryaRg1sBi0T_xleb-_jOOsNlJQ4Ze8U',
    appId: '1:847433846850:android:be77d9d841496e5a08dddb',
    messagingSenderId: '847433846850',
    projectId: 'cropsnew-22f87',
    storageBucket: 'cropsnew-22f87.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdumcVc26eIJJr_jtufMZUh6iN1XwvKKw',
    appId: '1:847433846850:ios:169709b0b050eedf08dddb',
    messagingSenderId: '847433846850',
    projectId: 'cropsnew-22f87',
    storageBucket: 'cropsnew-22f87.appspot.com',
    iosBundleId: 'com.example.crops',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWk-bD9ocDhaNGCF-fAUFvqYh5WE5PK6Y',
    appId: '1:847433846850:web:4c30ef021ac326c508dddb',
    messagingSenderId: '847433846850',
    projectId: 'cropsnew-22f87',
    authDomain: 'cropsnew-22f87.firebaseapp.com',
    storageBucket: 'cropsnew-22f87.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdumcVc26eIJJr_jtufMZUh6iN1XwvKKw',
    appId: '1:847433846850:ios:169709b0b050eedf08dddb',
    messagingSenderId: '847433846850',
    projectId: 'cropsnew-22f87',
    storageBucket: 'cropsnew-22f87.appspot.com',
    iosBundleId: 'com.example.crops',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWk-bD9ocDhaNGCF-fAUFvqYh5WE5PK6Y',
    appId: '1:847433846850:web:8ef464c25b6dcf0308dddb',
    messagingSenderId: '847433846850',
    projectId: 'cropsnew-22f87',
    authDomain: 'cropsnew-22f87.firebaseapp.com',
    storageBucket: 'cropsnew-22f87.appspot.com',
  );

}